//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.225
//     Generated on:    05.07.2016 11:05:23
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace RRTypes.kpt10 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1", IsNullable=false)]
    public partial class KPT : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private KPTCadastralBlocks cadastralBlocksField;
        
        /// <remarks/>
        public KPTCadastralBlocks CadastralBlocks {
            get {
                return this.cadastralBlocksField;
            }
            set {
                this.cadastralBlocksField = value;
                this.RaisePropertyChanged("CadastralBlocks");
            }
        }
        
        /// <summary />
        private KPTCertificationDoc certificationDocField;
        
        /// <remarks/>
        public KPTCertificationDoc CertificationDoc {
            get {
                return this.certificationDocField;
            }
            set {
                this.certificationDocField = value;
                this.RaisePropertyChanged("CertificationDoc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocks : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlock cadastralBlockField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlock CadastralBlock {
            get {
                return this.cadastralBlockField;
            }
            set {
                this.cadastralBlockField = value;
                this.RaisePropertyChanged("CadastralBlock");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlock : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockArea areaField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockArea Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelCollection parcelsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parcel", IsNullable=false)]
        public KPTCadastralBlocksCadastralBlockParcelCollection Parcels {
            get {
                return this.parcelsField;
            }
            set {
                this.parcelsField = value;
                this.RaisePropertyChanged("Parcels");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockObjectRealtyCollection objectsRealtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ObjectRealty", IsNullable=false)]
        public KPTCadastralBlocksCadastralBlockObjectRealtyCollection ObjectsRealty {
            get {
                return this.objectsRealtyField;
            }
            set {
                this.objectsRealtyField = value;
                this.RaisePropertyChanged("ObjectsRealty");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockOMSPoints oMSPointsField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockOMSPoints OMSPoints {
            get {
                return this.oMSPointsField;
            }
            set {
                this.oMSPointsField = value;
                this.RaisePropertyChanged("OMSPoints");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockSpatialData spatialDataField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockSpatialData SpatialData {
            get {
                return this.spatialDataField;
            }
            set {
                this.spatialDataField = value;
                this.RaisePropertyChanged("SpatialData");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockCoordSystems coordSystemsField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockCoordSystems CoordSystems {
            get {
                return this.coordSystemsField;
            }
            set {
                this.coordSystemsField = value;
                this.RaisePropertyChanged("CoordSystems");
            }
        }
        
        /// <summary />
        private string cadastralNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CadastralNumber {
            get {
                return this.cadastralNumberField;
            }
            set {
                this.cadastralNumberField = value;
                this.RaisePropertyChanged("CadastralNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockArea : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private decimal totalField;
        
        /// <remarks/>
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <summary />
        private byte unitField;
        
        /// <remarks/>
        public byte Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcel : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelArea areaField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockParcelArea Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <summary />
        private byte nameField;
        
        /// <remarks/>
        public byte Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelLocation locationField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockParcelLocation Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <summary />
        private uint categoryField;
        
        /// <remarks/>
        public uint Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelUtilization utilizationField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockParcelUtilization Utilization {
            get {
                return this.utilizationField;
            }
            set {
                this.utilizationField = value;
                this.RaisePropertyChanged("Utilization");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelContourCollection contoursField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Contour", IsNullable=false)]
        public KPTCadastralBlocksCadastralBlockParcelContourCollection Contours {
            get {
                return this.contoursField;
            }
            set {
                this.contoursField = value;
                this.RaisePropertyChanged("Contours");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelParentCadastralNumbers parentCadastralNumbersField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockParcelParentCadastralNumbers ParentCadastralNumbers {
            get {
                return this.parentCadastralNumbersField;
            }
            set {
                this.parentCadastralNumbersField = value;
                this.RaisePropertyChanged("ParentCadastralNumbers");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelCadastralCost cadastralCostField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockParcelCadastralCost CadastralCost {
            get {
                return this.cadastralCostField;
            }
            set {
                this.cadastralCostField = value;
                this.RaisePropertyChanged("CadastralCost");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelEntitySpatial entitySpatialField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockParcelEntitySpatial EntitySpatial {
            get {
                return this.entitySpatialField;
            }
            set {
                this.entitySpatialField = value;
                this.RaisePropertyChanged("EntitySpatial");
            }
        }
        
        /// <summary />
        private string cadastralNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CadastralNumber {
            get {
                return this.cadastralNumberField;
            }
            set {
                this.cadastralNumberField = value;
                this.RaisePropertyChanged("CadastralNumber");
            }
        }
        
        /// <summary />
        private byte stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <summary />
        private System.DateTime dateCreatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("DateCreated");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelArea : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private uint areaField;
        
        /// <remarks/>
        public uint Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <summary />
        private byte unitField;
        
        /// <remarks/>
        public byte Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <summary />
        private decimal inaccuracyField;
        
        /// <remarks/>
        public decimal Inaccuracy {
            get {
                return this.inaccuracyField;
            }
            set {
                this.inaccuracyField = value;
                this.RaisePropertyChanged("Inaccuracy");
            }
        }
        
        /// <summary />
        private bool inaccuracyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InaccuracySpecified {
            get {
                return this.inaccuracyFieldSpecified;
            }
            set {
                this.inaccuracyFieldSpecified = value;
                this.RaisePropertyChanged("InaccuracySpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelLocation : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private byte inBoundsField;
        
        /// <remarks/>
        public byte inBounds {
            get {
                return this.inBoundsField;
            }
            set {
                this.inBoundsField = value;
                this.RaisePropertyChanged("inBounds");
            }
        }
        
        /// <summary />
        private bool inBoundsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inBoundsSpecified {
            get {
                return this.inBoundsFieldSpecified;
            }
            set {
                this.inBoundsFieldSpecified = value;
                this.RaisePropertyChanged("inBoundsSpecified");
            }
        }
        
        /// <summary />
        private string placedField;
        
        /// <remarks/>
        public string Placed {
            get {
                return this.placedField;
            }
            set {
                this.placedField = value;
                this.RaisePropertyChanged("Placed");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelLocationAddress addressField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockParcelLocationAddress Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelLocationAddress : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private ulong oKATOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public ulong OKATO {
            get {
                return this.oKATOField;
            }
            set {
                this.oKATOField = value;
                this.RaisePropertyChanged("OKATO");
            }
        }
        
        /// <summary />
        private ulong kLADRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public ulong KLADR {
            get {
                return this.kLADRField;
            }
            set {
                this.kLADRField = value;
                this.RaisePropertyChanged("KLADR");
            }
        }
        
        /// <summary />
        private byte regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public byte Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <summary />
        private District districtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public District District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <summary />
        private Locality localityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public Locality Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
                this.RaisePropertyChanged("Locality");
            }
        }
        
        /// <summary />
        private Street streetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public Street Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <summary />
        private Level1 level1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public Level1 Level1 {
            get {
                return this.level1Field;
            }
            set {
                this.level1Field = value;
                this.RaisePropertyChanged("Level1");
            }
        }
        
        /// <summary />
        private Apartment apartmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public Apartment Apartment {
            get {
                return this.apartmentField;
            }
            set {
                this.apartmentField = value;
                this.RaisePropertyChanged("Apartment");
            }
        }
        
        /// <summary />
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
    public partial class District : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
    public partial class Locality : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
    public partial class Street : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
    public partial class Level1 : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <summary />
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
    public partial class Apartment : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <summary />
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelUtilization : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private ulong utilizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong Utilization {
            get {
                return this.utilizationField;
            }
            set {
                this.utilizationField = value;
                this.RaisePropertyChanged("Utilization");
            }
        }
        
        /// <summary />
        private string byDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ByDoc {
            get {
                return this.byDocField;
            }
            set {
                this.byDocField = value;
                this.RaisePropertyChanged("ByDoc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelContour : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockParcelContourEntitySpatial entitySpatialField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockParcelContourEntitySpatial EntitySpatial {
            get {
                return this.entitySpatialField;
            }
            set {
                this.entitySpatialField = value;
                this.RaisePropertyChanged("EntitySpatial");
            }
        }
        
        /// <summary />
        private byte numberRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NumberRecord {
            get {
                return this.numberRecordField;
            }
            set {
                this.numberRecordField = value;
                this.RaisePropertyChanged("NumberRecord");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelContourEntitySpatial : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private SpatialElementSpelementUnitCollection spatialElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
        [System.Xml.Serialization.XmlArrayItemAttribute("SpelementUnit", IsNullable=false)]
        public SpatialElementSpelementUnitCollection SpatialElement {
            get {
                return this.spatialElementField;
            }
            set {
                this.spatialElementField = value;
                this.RaisePropertyChanged("SpatialElement");
            }
        }
        
        /// <summary />
        private string entSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntSys {
            get {
                return this.entSysField;
            }
            set {
                this.entSysField = value;
                this.RaisePropertyChanged("EntSys");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
    public partial class SpatialElementSpelementUnit : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private SpatialElementSpelementUnitOrdinate ordinateField;
        
        /// <remarks/>
        public SpatialElementSpelementUnitOrdinate Ordinate {
            get {
                return this.ordinateField;
            }
            set {
                this.ordinateField = value;
                this.RaisePropertyChanged("Ordinate");
            }
        }
        
        /// <summary />
        private string typeUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeUnit {
            get {
                return this.typeUnitField;
            }
            set {
                this.typeUnitField = value;
                this.RaisePropertyChanged("TypeUnit");
            }
        }
        
        /// <summary />
        private byte suNmbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte SuNmb {
            get {
                return this.suNmbField;
            }
            set {
                this.suNmbField = value;
                this.RaisePropertyChanged("SuNmb");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
    public partial class SpatialElementSpelementUnitOrdinate : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private decimal xField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("X");
            }
        }
        
        /// <summary />
        private decimal yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("Y");
            }
        }
        
        /// <summary />
        private byte ordNmbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte OrdNmb {
            get {
                return this.ordNmbField;
            }
            set {
                this.ordNmbField = value;
                this.RaisePropertyChanged("OrdNmb");
            }
        }
        
        /// <summary />
        private decimal deltaGeopointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal DeltaGeopoint {
            get {
                return this.deltaGeopointField;
            }
            set {
                this.deltaGeopointField = value;
                this.RaisePropertyChanged("DeltaGeopoint");
            }
        }
        
        /// <summary />
        private bool deltaGeopointFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeltaGeopointSpecified {
            get {
                return this.deltaGeopointFieldSpecified;
            }
            set {
                this.deltaGeopointFieldSpecified = value;
                this.RaisePropertyChanged("DeltaGeopointSpecified");
            }
        }
        
        /// <summary />
        private string geopointZacrepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GeopointZacrep {
            get {
                return this.geopointZacrepField;
            }
            set {
                this.geopointZacrepField = value;
                this.RaisePropertyChanged("GeopointZacrep");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelParentCadastralNumbers : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string cadastralNumberField;
        
        /// <remarks/>
        public string CadastralNumber {
            get {
                return this.cadastralNumberField;
            }
            set {
                this.cadastralNumberField = value;
                this.RaisePropertyChanged("CadastralNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelCadastralCost : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <summary />
        private ushort unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelEntitySpatial : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private SpatialElementSpelementUnitCollection spatialElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
        [System.Xml.Serialization.XmlArrayItemAttribute("SpelementUnit", IsNullable=false)]
        public SpatialElementSpelementUnitCollection SpatialElement {
            get {
                return this.spatialElementField;
            }
            set {
                this.spatialElementField = value;
                this.RaisePropertyChanged("SpatialElement");
            }
        }
        
        /// <summary />
        private string entSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntSys {
            get {
                return this.entSysField;
            }
            set {
                this.entSysField = value;
                this.RaisePropertyChanged("EntSys");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockObjectRealty : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockObjectRealtyBuilding buildingField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockObjectRealtyBuilding Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("Building");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockObjectRealtyBuilding : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private uint objectTypeField;
        
        /// <remarks/>
        public uint ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
                this.RaisePropertyChanged("ObjectType");
            }
        }
        
        /// <summary />
        private ulong assignationBuildingField;
        
        /// <remarks/>
        public ulong AssignationBuilding {
            get {
                return this.assignationBuildingField;
            }
            set {
                this.assignationBuildingField = value;
                this.RaisePropertyChanged("AssignationBuilding");
            }
        }
        
        /// <summary />
        private decimal areaField;
        
        /// <remarks/>
        public decimal Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockObjectRealtyBuildingAddress addressField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockObjectRealtyBuildingAddress Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockObjectRealtyBuildingCadastralCost cadastralCostField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockObjectRealtyBuildingCadastralCost CadastralCost {
            get {
                return this.cadastralCostField;
            }
            set {
                this.cadastralCostField = value;
                this.RaisePropertyChanged("CadastralCost");
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockObjectRealtyBuildingEntitySpatial entitySpatialField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockObjectRealtyBuildingEntitySpatial EntitySpatial {
            get {
                return this.entitySpatialField;
            }
            set {
                this.entitySpatialField = value;
                this.RaisePropertyChanged("EntitySpatial");
            }
        }
        
        /// <summary />
        private string cadastralNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CadastralNumber {
            get {
                return this.cadastralNumberField;
            }
            set {
                this.cadastralNumberField = value;
                this.RaisePropertyChanged("CadastralNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockObjectRealtyBuildingAddress : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private ulong oKATOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public ulong OKATO {
            get {
                return this.oKATOField;
            }
            set {
                this.oKATOField = value;
                this.RaisePropertyChanged("OKATO");
            }
        }
        
        /// <summary />
        private ulong kLADRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public ulong KLADR {
            get {
                return this.kLADRField;
            }
            set {
                this.kLADRField = value;
                this.RaisePropertyChanged("KLADR");
            }
        }
        
        /// <summary />
        private uint postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public uint PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <summary />
        private bool postalCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostalCodeSpecified {
            get {
                return this.postalCodeFieldSpecified;
            }
            set {
                this.postalCodeFieldSpecified = value;
                this.RaisePropertyChanged("PostalCodeSpecified");
            }
        }
        
        /// <summary />
        private byte regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public byte Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <summary />
        private District districtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public District District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <summary />
        private Locality localityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public Locality Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
                this.RaisePropertyChanged("Locality");
            }
        }
        
        /// <summary />
        private Street streetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public Street Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <summary />
        private Level1 level1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public Level1 Level1 {
            get {
                return this.level1Field;
            }
            set {
                this.level1Field = value;
                this.RaisePropertyChanged("Level1");
            }
        }
        
        /// <summary />
        private Level2 level2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public Level2 Level2 {
            get {
                return this.level2Field;
            }
            set {
                this.level2Field = value;
                this.RaisePropertyChanged("Level2");
            }
        }
        
        /// <summary />
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/address-output/4.0.1")]
    public partial class Level2 : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <summary />
        private byte valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockObjectRealtyBuildingCadastralCost : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <summary />
        private ushort unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockObjectRealtyBuildingEntitySpatial : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private SpatialElementSpelementUnitCollection spatialElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
        [System.Xml.Serialization.XmlArrayItemAttribute("SpelementUnit", IsNullable=false)]
        public SpatialElementSpelementUnitCollection SpatialElement {
            get {
                return this.spatialElementField;
            }
            set {
                this.spatialElementField = value;
                this.RaisePropertyChanged("SpatialElement");
            }
        }
        
        /// <summary />
        private string entSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntSys {
            get {
                return this.entSysField;
            }
            set {
                this.entSysField = value;
                this.RaisePropertyChanged("EntSys");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockOMSPoints : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockOMSPointsOMSPoint oMSPointField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockOMSPointsOMSPoint OMSPoint {
            get {
                return this.oMSPointField;
            }
            set {
                this.oMSPointField = value;
                this.RaisePropertyChanged("OMSPoint");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockOMSPointsOMSPoint : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private uint pNmbField;
        
        /// <remarks/>
        public uint PNmb {
            get {
                return this.pNmbField;
            }
            set {
                this.pNmbField = value;
                this.RaisePropertyChanged("PNmb");
            }
        }
        
        /// <summary />
        private string pNameField;
        
        /// <remarks/>
        public string PName {
            get {
                return this.pNameField;
            }
            set {
                this.pNameField = value;
                this.RaisePropertyChanged("PName");
            }
        }
        
        /// <summary />
        private string pKlassField;
        
        /// <remarks/>
        public string PKlass {
            get {
                return this.pKlassField;
            }
            set {
                this.pKlassField = value;
                this.RaisePropertyChanged("PKlass");
            }
        }
        
        /// <summary />
        private decimal ordXField;
        
        /// <remarks/>
        public decimal OrdX {
            get {
                return this.ordXField;
            }
            set {
                this.ordXField = value;
                this.RaisePropertyChanged("OrdX");
            }
        }
        
        /// <summary />
        private decimal ordYField;
        
        /// <remarks/>
        public decimal OrdY {
            get {
                return this.ordYField;
            }
            set {
                this.ordYField = value;
                this.RaisePropertyChanged("OrdY");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockSpatialData : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private KPTCadastralBlocksCadastralBlockSpatialDataEntitySpatial entitySpatialField;
        
        /// <remarks/>
        public KPTCadastralBlocksCadastralBlockSpatialDataEntitySpatial EntitySpatial {
            get {
                return this.entitySpatialField;
            }
            set {
                this.entitySpatialField = value;
                this.RaisePropertyChanged("EntitySpatial");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockSpatialDataEntitySpatial : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private SpatialElementSpelementUnitCollection spatialElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
        [System.Xml.Serialization.XmlArrayItemAttribute("SpelementUnit", IsNullable=false)]
        public SpatialElementSpelementUnitCollection SpatialElement {
            get {
                return this.spatialElementField;
            }
            set {
                this.spatialElementField = value;
                this.RaisePropertyChanged("SpatialElement");
            }
        }
        
        /// <summary />
        private string entSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntSys {
            get {
                return this.entSysField;
            }
            set {
                this.entSysField = value;
                this.RaisePropertyChanged("EntSys");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockCoordSystems : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private CoordSystem coordSystemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
        public CoordSystem CoordSystem {
            get {
                return this.coordSystemField;
            }
            set {
                this.coordSystemField = value;
                this.RaisePropertyChanged("CoordSystem");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
    public partial class CoordSystem : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string csIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CsId {
            get {
                return this.csIdField;
            }
            set {
                this.csIdField = value;
                this.RaisePropertyChanged("CsId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCertificationDoc : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string organizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/certification-doc/1.0")]
        public string Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
                this.RaisePropertyChanged("Organization");
            }
        }
        
        /// <summary />
        private System.DateTime dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/certification-doc/1.0", DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <summary />
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/certification-doc/1.0")]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <summary />
        private Official officialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/certification-doc/1.0")]
        public Official Official {
            get {
                return this.officialField;
            }
            set {
                this.officialField = value;
                this.RaisePropertyChanged("Official");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/certification-doc/1.0")]
    public partial class Official : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string appointmentField;
        
        /// <remarks/>
        public string Appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
                this.RaisePropertyChanged("Appointment");
            }
        }
        
        /// <summary />
        private string familyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
                this.RaisePropertyChanged("FamilyName");
            }
        }
        
        /// <summary />
        private string firstNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <summary />
        private string patronymicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string Patronymic {
            get {
                return this.patronymicField;
            }
            set {
                this.patronymicField = value;
                this.RaisePropertyChanged("Patronymic");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelCollection : System.Collections.Generic.List<KPTCadastralBlocksCadastralBlockParcel> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockObjectRealtyCollection : System.Collections.Generic.List<KPTCadastralBlocksCadastralBlockObjectRealty> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/outgoing/kpt/10.0.1")]
    public partial class KPTCadastralBlocksCadastralBlockParcelContourCollection : System.Collections.Generic.List<KPTCadastralBlocksCadastralBlockParcelContour> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/entity-spatial/5.0.1")]
    public partial class SpatialElementSpelementUnitCollection : System.Collections.Generic.List<SpatialElementSpelementUnit> {
    }
}
#pragma warning restore 1591