//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.225
//     Generated on:    14.06.2018 14:27:04
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace RRTypes {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0", IsNullable=false)]
    public partial class XMLDocumentInfo_deprecated : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public XMLDocumentInfo_deprecated() {
            this.producerField = "Fixosoft";
        }
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private tBlockCollection blockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Block")]
        public tBlockCollection Block {
            get {
                return this.blockField;
            }
            set {
                this.blockField = value;
                this.RaisePropertyChanged("Block");
            }
        }
        
        /// <summary />
        private string parcelsCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParcelsCount {
            get {
                return this.parcelsCountField;
            }
            set {
                this.parcelsCountField = value;
                this.RaisePropertyChanged("ParcelsCount");
            }
        }
        
        /// <summary />
        private string blocksCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BlocksCount {
            get {
                return this.blocksCountField;
            }
            set {
                this.blocksCountField = value;
                this.RaisePropertyChanged("BlocksCount");
            }
        }
        
        /// <summary />
        private string docRootNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocRootName {
            get {
                return this.docRootNameField;
            }
            set {
                this.docRootNameField = value;
                this.RaisePropertyChanged("DocRootName");
            }
        }
        
        /// <summary />
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <summary />
        private string namespaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
                this.RaisePropertyChanged("Namespace");
            }
        }
        
        /// <summary />
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <summary />
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
                this.RaisePropertyChanged("FilePath");
            }
        }
        
        /// <summary />
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <summary />
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <summary />
        private string docTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <summary />
        private string appointmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
                this.RaisePropertyChanged("Appointment");
            }
        }
        
        /// <summary />
        private string fIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FIO {
            get {
                return this.fIOField;
            }
            set {
                this.fIOField = value;
                this.RaisePropertyChanged("FIO");
            }
        }
        
        /// <summary />
        private string parserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parser {
            get {
                return this.parserField;
            }
            set {
                this.parserField = value;
                this.RaisePropertyChanged("Parser");
            }
        }
        
        /// <summary />
        private string parsedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParsedDate {
            get {
                return this.parsedDateField;
            }
            set {
                this.parsedDateField = value;
                this.RaisePropertyChanged("ParsedDate");
            }
        }
        
        /// <summary />
        private string producerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Producer {
            get {
                return this.producerField;
            }
            set {
                this.producerField = value;
                this.RaisePropertyChanged("Producer");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0", IsNullable=true)]
    public partial class tBlock : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private tParcelCollection parcelsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parcels")]
        public tParcelCollection Parcels {
            get {
                return this.parcelsField;
            }
            set {
                this.parcelsField = value;
                this.RaisePropertyChanged("Parcels");
            }
        }
        
        /// <summary />
        private string blockCadastalNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BlockCadastalNumber {
            get {
                return this.blockCadastalNumberField;
            }
            set {
                this.blockCadastalNumberField = value;
                this.RaisePropertyChanged("BlockCadastalNumber");
            }
        }
        
        /// <summary />
        private string parcelsCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParcelsCount {
            get {
                return this.parcelsCountField;
            }
            set {
                this.parcelsCountField = value;
                this.RaisePropertyChanged("ParcelsCount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0", IsNullable=true)]
    public partial class tParcel : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string parcelCadastalNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParcelCadastalNumber {
            get {
                return this.parcelCadastalNumberField;
            }
            set {
                this.parcelCadastalNumberField = value;
                this.RaisePropertyChanged("ParcelCadastalNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0", IsNullable=true)]
    public partial class tCadastralBlocks : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private tBlockCollection blockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Block")]
        public tBlockCollection Block {
            get {
                return this.blockField;
            }
            set {
                this.blockField = value;
                this.RaisePropertyChanged("Block");
            }
        }
        
        /// <summary />
        private string blockCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BlockCount {
            get {
                return this.blockCountField;
            }
            set {
                this.blockCountField = value;
                this.RaisePropertyChanged("BlockCount");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0")]
    public partial class tBlockCollection : System.Collections.Generic.List<tBlock> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-fixosoft-ru/XMLDocumentInfo/1.0")]
    public partial class tParcelCollection : System.Collections.Generic.List<tParcel> {
    }
}
#pragma warning restore 1591