//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.1
//     Generated on:    07.02.2015 11:02:16
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace XMLReaderCS.XSD_Schemes {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-fixosoft-ru/MyCertification-doc/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-fixosoft-ru/MyCertification-doc/1.0", IsNullable=true)]
    public partial class tMyCertificationDoc : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string xMLDocumentInfoField;
        
        /// <remarks/>
        public string XMLDocumentInfo {
            get {
                return this.xMLDocumentInfoField;
            }
            set {
                this.xMLDocumentInfoField = value;
                this.RaisePropertyChanged("XMLDocumentInfo");
            }
        }
        
        /// <summary />
        private string dateField;
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <summary />
        private string numberField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <summary />
        private string appointmentField;
        
        /// <remarks/>
        public string Appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
                this.RaisePropertyChanged("Appointment");
            }
        }
        
        /// <summary />
        private string fIOField;
        
        /// <remarks/>
        public string FIO {
            get {
                return this.fIOField;
            }
            set {
                this.fIOField = value;
                this.RaisePropertyChanged("FIO");
            }
        }
    }
}
#pragma warning restore 1591