//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.225
//     Generated on:    13.03.2015 13:41:48
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace InspectorAct {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1", IsNullable=false)]
    public partial class InspectionAct : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private InspectionActContractor contractorField;
        
        /// <remarks/>
        public InspectionActContractor Contractor {
            get {
                return this.contractorField;
            }
            set {
                this.contractorField = value;
                this.RaisePropertyChanged("Contractor");
            }
        }
        
        /// <summary />
        private tClient clientField;
        
        /// <remarks/>
        public tClient Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <summary />
        private tObject objectField;
        
        /// <remarks/>
        public tObject Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
                this.RaisePropertyChanged("Object");
            }
        }
        
        /// <summary />
        private tDocumentCollection documentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
        public tDocumentCollection Documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
                this.RaisePropertyChanged("Documents");
            }
        }
        
        /// <summary />
        private string conclusionField;
        
        /// <remarks/>
        public string Conclusion {
            get {
                return this.conclusionField;
            }
            set {
                this.conclusionField = value;
                this.RaisePropertyChanged("Conclusion");
            }
        }
        
        /// <summary />
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <summary />
        private string nameSoftwareField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSoftware {
            get {
                return this.nameSoftwareField;
            }
            set {
                this.nameSoftwareField = value;
                this.RaisePropertyChanged("NameSoftware");
            }
        }
        
        /// <summary />
        private string versionSoftwareField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VersionSoftware {
            get {
                return this.versionSoftwareField;
            }
            set {
                this.versionSoftwareField = value;
                this.RaisePropertyChanged("VersionSoftware");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1")]
    public partial class InspectionActContractor : tEngineer {
        
        /// <summary />
        private System.DateTime dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/cadastral-engineer/1.0.2")]
    public partial class tEngineer : tCadastralEngineer {
        
        /// <summary />
        private tOrganization organizationField;
        
        /// <remarks/>
        public tOrganization Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
                this.RaisePropertyChanged("Organization");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/cadastral-engineer/1.0.2")]
    public partial class tOrganization : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string addressOrganizationField;
        
        /// <remarks/>
        public string AddressOrganization {
            get {
                return this.addressOrganizationField;
            }
            set {
                this.addressOrganizationField = value;
                this.RaisePropertyChanged("AddressOrganization");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/document/1.0.1")]
    public partial class tAppliedFile : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private dApplied_file kindField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dApplied_file Kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
                this.RaisePropertyChanged("Kind");
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/directories/applied-file/1.0.1")]
    public enum dApplied_file {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/document/1.0.1")]
    public partial class tDocument : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private dAllDocuments codeDocumentField;
        
        /// <remarks/>
        public dAllDocuments CodeDocument {
            get {
                return this.codeDocumentField;
            }
            set {
                this.codeDocumentField = value;
                this.RaisePropertyChanged("CodeDocument");
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string seriesField;
        
        /// <remarks/>
        public string Series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
                this.RaisePropertyChanged("Series");
            }
        }
        
        /// <summary />
        private string numberField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <summary />
        private System.DateTime dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <summary />
        private string issueOrganField;
        
        /// <remarks/>
        public string IssueOrgan {
            get {
                return this.issueOrganField;
            }
            set {
                this.issueOrganField = value;
                this.RaisePropertyChanged("IssueOrgan");
            }
        }
        
        /// <summary />
        private string descField;
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <summary />
        private tAppliedFile appliedFileField;
        
        /// <remarks/>
        public tAppliedFile AppliedFile {
            get {
                return this.appliedFileField;
            }
            set {
                this.appliedFileField = value;
                this.RaisePropertyChanged("AppliedFile");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/directories/all-documents/1.0.1")]
    public enum dAllDocuments {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001000000")]
        Item008001000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001001000")]
        Item008001001000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001002000")]
        Item008001002000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001003000")]
        Item008001003000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001004000")]
        Item008001004000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001005000")]
        Item008001005000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001006000")]
        Item008001006000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001007000")]
        Item008001007000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001008000")]
        Item008001008000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001009000")]
        Item008001009000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001010000")]
        Item008001010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001011000")]
        Item008001011000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001012000")]
        Item008001012000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001013000")]
        Item008001013000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001014000")]
        Item008001014000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001015000")]
        Item008001015000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001016000")]
        Item008001016000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001017000")]
        Item008001017000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001018000")]
        Item008001018000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001019000")]
        Item008001019000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001020000")]
        Item008001020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008001099000")]
        Item008001099000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002000000")]
        Item008002000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002001000")]
        Item008002001000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002002000")]
        Item008002002000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002004000")]
        Item008002004000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002005000")]
        Item008002005000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002006000")]
        Item008002006000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002007000")]
        Item008002007000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002008000")]
        Item008002008000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008002099000")]
        Item008002099000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("555001000000")]
        Item555001000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("555002000000")]
        Item555002000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("555003000000")]
        Item555003000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("555004000000")]
        Item555004000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("555005000000")]
        Item555005000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558100000000")]
        Item558100000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101000000")]
        Item558101000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101010000")]
        Item558101010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101020000")]
        Item558101020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101030000")]
        Item558101030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101060000")]
        Item558101060000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101070000")]
        Item558101070000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101090000")]
        Item558101090000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101090100")]
        Item558101090100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101090200")]
        Item558101090200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101100000")]
        Item558101100000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101110000")]
        Item558101110000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101120000")]
        Item558101120000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558101130000")]
        Item558101130000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102000000")]
        Item558102000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102010000")]
        Item558102010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102100000")]
        Item558102100000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102110000")]
        Item558102110000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102140000")]
        Item558102140000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102150000")]
        Item558102150000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102160000")]
        Item558102160000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102170000")]
        Item558102170000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102180000")]
        Item558102180000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102190000")]
        Item558102190000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558102200000")]
        Item558102200000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558104000000")]
        Item558104000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558200000000")]
        Item558200000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558203000000")]
        Item558203000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558204000000")]
        Item558204000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558205000000")]
        Item558205000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558205010000")]
        Item558205010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558205020000")]
        Item558205020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558205030000")]
        Item558205030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558205040000")]
        Item558205040000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558206000000")]
        Item558206000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558207000000")]
        Item558207000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558208000000")]
        Item558208000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558209000000")]
        Item558209000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558211000000")]
        Item558211000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558211010000")]
        Item558211010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558211020000")]
        Item558211020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558211040000")]
        Item558211040000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558212000000")]
        Item558212000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558213000000")]
        Item558213000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558213010000")]
        Item558213010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558213020000")]
        Item558213020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558213030000")]
        Item558213030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558214000000")]
        Item558214000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558214010000")]
        Item558214010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558214020000")]
        Item558214020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558216000000")]
        Item558216000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558217000000")]
        Item558217000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558218000000")]
        Item558218000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558219000000")]
        Item558219000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221000000")]
        Item558221000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221010000")]
        Item558221010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221020000")]
        Item558221020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221030000")]
        Item558221030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221040000")]
        Item558221040000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221050000")]
        Item558221050000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221060000")]
        Item558221060000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221070000")]
        Item558221070000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221080000")]
        Item558221080000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558221990000")]
        Item558221990000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558300000000")]
        Item558300000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301000000")]
        Item558301000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301010000")]
        Item558301010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301020000")]
        Item558301020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301030000")]
        Item558301030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301040000")]
        Item558301040000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301050000")]
        Item558301050000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301060000")]
        Item558301060000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301070000")]
        Item558301070000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301080000")]
        Item558301080000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301090000")]
        Item558301090000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301100000")]
        Item558301100000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301110000")]
        Item558301110000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301120000")]
        Item558301120000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301130000")]
        Item558301130000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301140000")]
        Item558301140000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558301990000")]
        Item558301990000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558400000000")]
        Item558400000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401000000")]
        Item558401000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010000")]
        Item558401010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010100")]
        Item558401010100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010101")]
        Item558401010101,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010102")]
        Item558401010102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010103")]
        Item558401010103,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010104")]
        Item558401010104,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010105")]
        Item558401010105,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010106")]
        Item558401010106,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010200")]
        Item558401010200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010201")]
        Item558401010201,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010202")]
        Item558401010202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010203")]
        Item558401010203,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010204")]
        Item558401010204,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010205")]
        Item558401010205,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010206")]
        Item558401010206,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010207")]
        Item558401010207,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010208")]
        Item558401010208,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010209")]
        Item558401010209,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010210")]
        Item558401010210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010211")]
        Item558401010211,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010212")]
        Item558401010212,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010213")]
        Item558401010213,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010214")]
        Item558401010214,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010215")]
        Item558401010215,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010216")]
        Item558401010216,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010217")]
        Item558401010217,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010218")]
        Item558401010218,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010219")]
        Item558401010219,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010220")]
        Item558401010220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401010299")]
        Item558401010299,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401020000")]
        Item558401020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401020100")]
        Item558401020100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401020200")]
        Item558401020200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401020300")]
        Item558401020300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401020400")]
        Item558401020400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401029900")]
        Item558401029900,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401030000")]
        Item558401030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401030100")]
        Item558401030100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401030200")]
        Item558401030200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401040000")]
        Item558401040000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401050000")]
        Item558401050000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401050100")]
        Item558401050100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401050200")]
        Item558401050200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401050300")]
        Item558401050300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401050400")]
        Item558401050400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401059900")]
        Item558401059900,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401060000")]
        Item558401060000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401060100")]
        Item558401060100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401060200")]
        Item558401060200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401060300")]
        Item558401060300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401070000")]
        Item558401070000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401070100")]
        Item558401070100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401070200")]
        Item558401070200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401070300")]
        Item558401070300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080000")]
        Item558401080000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080100")]
        Item558401080100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080200")]
        Item558401080200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080300")]
        Item558401080300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080400")]
        Item558401080400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080500")]
        Item558401080500,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080600")]
        Item558401080600,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080700")]
        Item558401080700,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080800")]
        Item558401080800,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401080900")]
        Item558401080900,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401081000")]
        Item558401081000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401081100")]
        Item558401081100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401081200")]
        Item558401081200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558401089900")]
        Item558401089900,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402000000")]
        Item558402000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402010000")]
        Item558402010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402020000")]
        Item558402020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402030000")]
        Item558402030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402040000")]
        Item558402040000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402050000")]
        Item558402050000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402060000")]
        Item558402060000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402070000")]
        Item558402070000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402080000")]
        Item558402080000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402090000")]
        Item558402090000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402100000")]
        Item558402100000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402110000")]
        Item558402110000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402120000")]
        Item558402120000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402130000")]
        Item558402130000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402140000")]
        Item558402140000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402150000")]
        Item558402150000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402160000")]
        Item558402160000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402170000")]
        Item558402170000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402180000")]
        Item558402180000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402190000")]
        Item558402190000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402200000")]
        Item558402200000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402210000")]
        Item558402210000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402220000")]
        Item558402220000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402230000")]
        Item558402230000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402240000")]
        Item558402240000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402250000")]
        Item558402250000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402260000")]
        Item558402260000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402270000")]
        Item558402270000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402280000")]
        Item558402280000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402390000")]
        Item558402390000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402400000")]
        Item558402400000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558402990000")]
        Item558402990000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403000000")]
        Item558403000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403010000")]
        Item558403010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403020000")]
        Item558403020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403030000")]
        Item558403030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403040000")]
        Item558403040000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403050000")]
        Item558403050000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403060000")]
        Item558403060000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403070000")]
        Item558403070000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403080000")]
        Item558403080000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403090000")]
        Item558403090000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403100000")]
        Item558403100000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403110000")]
        Item558403110000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558403990000")]
        Item558403990000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558500000000")]
        Item558500000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501000000")]
        Item558501000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501010000")]
        Item558501010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501010100")]
        Item558501010100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501010500")]
        Item558501010500,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501010600")]
        Item558501010600,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501010700")]
        Item558501010700,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501010900")]
        Item558501010900,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501011000")]
        Item558501011000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501011100")]
        Item558501011100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501020000")]
        Item558501020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501020100")]
        Item558501020100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501020200")]
        Item558501020200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501020500")]
        Item558501020500,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501020700")]
        Item558501020700,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501020800")]
        Item558501020800,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501020900")]
        Item558501020900,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501021000")]
        Item558501021000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501021100")]
        Item558501021100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501021200")]
        Item558501021200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501030000")]
        Item558501030000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501030100")]
        Item558501030100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501030200")]
        Item558501030200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501030300")]
        Item558501030300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501030400")]
        Item558501030400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558501039900")]
        Item558501039900,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502000000")]
        Item558502000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010000")]
        Item558502010000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010100")]
        Item558502010100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010200")]
        Item558502010200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010300")]
        Item558502010300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010400")]
        Item558502010400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010500")]
        Item558502010500,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010600")]
        Item558502010600,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010700")]
        Item558502010700,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010800")]
        Item558502010800,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502010900")]
        Item558502010900,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502011000")]
        Item558502011000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502011100")]
        Item558502011100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502011200")]
        Item558502011200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502011300")]
        Item558502011300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502011400")]
        Item558502011400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502020000")]
        Item558502020000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502020100")]
        Item558502020100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("558502029900")]
        Item558502029900,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1", IsNullable=true)]
    public partial class tObject : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string cadastralNumberField;
        
        /// <remarks/>
        public string CadastralNumber {
            get {
                return this.cadastralNumberField;
            }
            set {
                this.cadastralNumberField = value;
                this.RaisePropertyChanged("CadastralNumber");
            }
        }
        
        /// <summary />
        private tObjectObjectType objectTypeField;
        
        /// <remarks/>
        public tObjectObjectType ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
                this.RaisePropertyChanged("ObjectType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/directories/realty/1.0.1")]
    public enum tObjectObjectType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002001000000")]
        Item002001000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002001001000")]
        Item002001001000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002001002000")]
        Item002001002000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002001003000")]
        Item002001003000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002001004000")]
        Item002001004000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002001005000")]
        Item002001005000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002001006000")]
        Item002001006000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002001007000")]
        Item002001007000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002002000000")]
        Item002002000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002002001000")]
        Item002002001000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002002002000")]
        Item002002002000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002002003000")]
        Item002002003000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002002004000")]
        Item002002004000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002003000000")]
        Item002003000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002003001000")]
        Item002003001000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002003002000")]
        Item002003002000,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1", IsNullable=true)]
    public partial class tClient : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForeignOrganization", typeof(tClientForeignOrganization))]
        [System.Xml.Serialization.XmlElementAttribute("Governance", typeof(tClientGovernance))]
        [System.Xml.Serialization.XmlElementAttribute("Organization", typeof(tClientOrganization))]
        [System.Xml.Serialization.XmlElementAttribute("Person", typeof(tClientPerson))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1")]
    public partial class tClientForeignOrganization : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string countryField;
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1")]
    public partial class tClientGovernance : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1")]
    public partial class tClientOrganization : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-rosreestr-ru/incoming/inspection/1.0.1")]
    public partial class tClientPerson : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string familyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
                this.RaisePropertyChanged("FamilyName");
            }
        }
        
        /// <summary />
        private string firstNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <summary />
        private string patronymicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string Patronymic {
            get {
                return this.patronymicField;
            }
            set {
                this.patronymicField = value;
                this.RaisePropertyChanged("Patronymic");
            }
        }
        
        /// <summary />
        private string sNILSField;
        
        /// <remarks/>
        public string SNILS {
            get {
                return this.sNILSField;
            }
            set {
                this.sNILSField = value;
                this.RaisePropertyChanged("SNILS");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tEngineer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/cadastral-engineer/1.0.2")]
    public partial class tCadastralEngineer : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string familyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
                this.RaisePropertyChanged("FamilyName");
            }
        }
        
        /// <summary />
        private string firstNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <summary />
        private string patronymicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string Patronymic {
            get {
                return this.patronymicField;
            }
            set {
                this.patronymicField = value;
                this.RaisePropertyChanged("Patronymic");
            }
        }
        
        /// <summary />
        private string nCertificateField;
        
        /// <remarks/>
        public string NCertificate {
            get {
                return this.nCertificateField;
            }
            set {
                this.nCertificateField = value;
                this.RaisePropertyChanged("NCertificate");
            }
        }
        
        /// <summary />
        private string telephoneField;
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
                this.RaisePropertyChanged("Telephone");
            }
        }
        
        /// <summary />
        private string addressField;
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <summary />
        private string emailField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-rosreestr-ru/commons/complex-types/document/1.0.1")]
    public partial class tDocumentCollection : System.Collections.Generic.List<tDocument> {
    }
}
#pragma warning restore 1591