//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.225
//     Generated on:    24.05.2016 9:00:36
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace RRTypes.SKPT01 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SchemaParcels : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private SchemaParcelsEDocument eDocumentField;
        
        /// <remarks/>
        public SchemaParcelsEDocument eDocument {
            get {
                return this.eDocumentField;
            }
            set {
                this.eDocumentField = value;
                this.RaisePropertyChanged("eDocument");
            }
        }
        
        /// <summary />
        private SchemaParcelsDocument documentField;
        
        /// <remarks/>
        public SchemaParcelsDocument Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <summary />
        private tNewParcelCollection newParcelsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NewParcel", IsNullable=false)]
        public tNewParcelCollection NewParcels {
            get {
                return this.newParcelsField;
            }
            set {
                this.newParcelsField = value;
                this.RaisePropertyChanged("NewParcels");
            }
        }
        
        /// <summary />
        private Coord_Systems coord_SystemsField;
        
        /// <remarks/>
        public Coord_Systems Coord_Systems {
            get {
                return this.coord_SystemsField;
            }
            set {
                this.coord_SystemsField = value;
                this.RaisePropertyChanged("Coord_Systems");
            }
        }
        
        /// <summary />
        private SchemaParcelsAppliedFileCollection parcelSchema_In_BlockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AppliedFile", IsNullable=false)]
        public SchemaParcelsAppliedFileCollection ParcelSchema_In_Block {
            get {
                return this.parcelSchema_In_BlockField;
            }
            set {
                this.parcelSchema_In_BlockField = value;
                this.RaisePropertyChanged("ParcelSchema_In_Block");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SchemaParcelsEDocument : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public SchemaParcelsEDocument() {
            this.versionField = "01";
        }
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <summary />
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class tCategory : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private dCategories categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dCategories Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    public enum dCategories {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003001000000")]
        Item003001000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003002000000")]
        Item003002000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003003000000")]
        Item003003000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003004000000")]
        Item003004000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003005000000")]
        Item003005000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003006000000")]
        Item003006000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003007000000")]
        Item003007000000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003008000000")]
        Item003008000000,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class tUtilization : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string byDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ByDoc {
            get {
                return this.byDocField;
            }
            set {
                this.byDocField = value;
                this.RaisePropertyChanged("ByDoc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class tOrdinate_short : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string xField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("X");
            }
        }
        
        /// <summary />
        private string yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("Y");
            }
        }
        
        /// <summary />
        private string num_GeopointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string Num_Geopoint {
            get {
                return this.num_GeopointField;
            }
            set {
                this.num_GeopointField = value;
                this.RaisePropertyChanged("Num_Geopoint");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class tSPELEMENT_UNIT_SHORT : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public tSPELEMENT_UNIT_SHORT() {
            this.type_UnitField = tSPELEMENT_UNIT_SHORTType_Unit.Точка;
        }
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private tOrdinate_short newOrdinateField;
        
        /// <remarks/>
        public tOrdinate_short NewOrdinate {
            get {
                return this.newOrdinateField;
            }
            set {
                this.newOrdinateField = value;
                this.RaisePropertyChanged("NewOrdinate");
            }
        }
        
        /// <summary />
        private tSPELEMENT_UNIT_SHORTType_Unit type_UnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tSPELEMENT_UNIT_SHORTType_Unit Type_Unit {
            get {
                return this.type_UnitField;
            }
            set {
                this.type_UnitField = value;
                this.RaisePropertyChanged("Type_Unit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    public enum tSPELEMENT_UNIT_SHORTType_Unit {
        
        /// <remarks/>
        Точка,
        
        /// <remarks/>
        Линия,
        
        /// <remarks/>
        Дуга,
        
        /// <remarks/>
        Прямоугольник,
        
        /// <remarks/>
        Окружность,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class tAreaProject : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public tAreaProject() {
            this.unitField = dUnit.Item055;
        }
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string areaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <summary />
        private dUnit unitField;
        
        /// <remarks/>
        public dUnit Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    public enum dUnit {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("008")]
        Item008,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("047")]
        Item047,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("050")]
        Item050,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("051")]
        Item051,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("053")]
        Item053,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("055")]
        Item055,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("058")]
        Item058,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("059")]
        Item059,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("061")]
        Item061,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("109")]
        Item109,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("359")]
        Item359,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("360")]
        Item360,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("361")]
        Item361,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("362")]
        Item362,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("364")]
        Item364,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("365")]
        Item365,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("366")]
        Item366,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("383")]
        Item383,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("384")]
        Item384,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("385")]
        Item385,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("386")]
        Item386,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1000")]
        Item1000,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1001")]
        Item1001,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1002")]
        Item1002,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1003")]
        Item1003,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1004")]
        Item1004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1005")]
        Item1005,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class tNewParcel : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string cadastralBlockField;
        
        /// <remarks/>
        public string CadastralBlock {
            get {
                return this.cadastralBlockField;
            }
            set {
                this.cadastralBlockField = value;
                this.RaisePropertyChanged("CadastralBlock");
            }
        }
        
        /// <summary />
        private tAreaProject areaField;
        
        /// <remarks/>
        public tAreaProject Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <summary />
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contours", typeof(tNewParcelContours))]
        [System.Xml.Serialization.XmlElementAttribute("Entity_Spatial", typeof(Entity_Spatial))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <summary />
        private string[] prev_CadastralNumbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CadastralNumber", IsNullable=false)]
        public string[] Prev_CadastralNumbers {
            get {
                return this.prev_CadastralNumbersField;
            }
            set {
                this.prev_CadastralNumbersField = value;
                this.RaisePropertyChanged("Prev_CadastralNumbers");
            }
        }
        
        /// <summary />
        private string noteField;
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <summary />
        private object item1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TerritorialZone", typeof(tNewParcelTerritorialZone))]
        [System.Xml.Serialization.XmlElementAttribute("Utilization", typeof(tUtilization))]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        /// <summary />
        private tCategory categoryField;
        
        /// <remarks/>
        public tCategory Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <summary />
        private string definitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Definition {
            get {
                return this.definitionField;
            }
            set {
                this.definitionField = value;
                this.RaisePropertyChanged("Definition");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class tNewParcelContours : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private tNewParcelContoursContourCollection contourField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contour")]
        public tNewParcelContoursContourCollection Contour {
            get {
                return this.contourField;
            }
            set {
                this.contourField = value;
                this.RaisePropertyChanged("Contour");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class tNewParcelContoursContour : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private Entity_Spatial entity_SpatialField;
        
        /// <remarks/>
        public Entity_Spatial Entity_Spatial {
            get {
                return this.entity_SpatialField;
            }
            set {
                this.entity_SpatialField = value;
                this.RaisePropertyChanged("Entity_Spatial");
            }
        }
        
        /// <summary />
        private string definitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Definition {
            get {
                return this.definitionField;
            }
            set {
                this.definitionField = value;
                this.RaisePropertyChanged("Definition");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Entity_Spatial : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private tSPELEMENT_UNIT_SHORTCollection spatial_ElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Spelement_Unit", typeof(tSPELEMENT_UNIT_SHORT), IsNullable=false)]
        public tSPELEMENT_UNIT_SHORTCollection Spatial_Element {
            get {
                return this.spatial_ElementField;
            }
            set {
                this.spatial_ElementField = value;
                this.RaisePropertyChanged("Spatial_Element");
            }
        }
        
        /// <summary />
        private string ent_SysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string Ent_Sys {
            get {
                return this.ent_SysField;
            }
            set {
                this.ent_SysField = value;
                this.RaisePropertyChanged("Ent_Sys");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class tNewParcelTerritorialZone : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string accountNumberField;
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <summary />
        private string nameZoneField;
        
        /// <remarks/>
        public string NameZone {
            get {
                return this.nameZoneField;
            }
            set {
                this.nameZoneField = value;
                this.RaisePropertyChanged("NameZone");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SchemaParcelsDocument : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string numberField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <summary />
        private System.DateTime dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <summary />
        private string[] issueOrgansField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("IssueOrgan", IsNullable=false)]
        public string[] IssueOrgans {
            get {
                return this.issueOrgansField;
            }
            set {
                this.issueOrgansField = value;
                this.RaisePropertyChanged("IssueOrgans");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Coord_Systems : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private Coord_System coord_SystemField;
        
        /// <remarks/>
        public Coord_System Coord_System {
            get {
                return this.coord_SystemField;
            }
            set {
                this.coord_SystemField = value;
                this.RaisePropertyChanged("Coord_System");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Coord_System : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string cs_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Cs_Id {
            get {
                return this.cs_IdField;
            }
            set {
                this.cs_IdField = value;
                this.RaisePropertyChanged("Cs_Id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SchemaParcelsAppliedFile : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class tSPATIAL_ELEMENT_SHORT : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private tSPELEMENT_UNIT_SHORTCollection spelement_UnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Spelement_Unit")]
        public tSPELEMENT_UNIT_SHORTCollection Spelement_Unit {
            get {
                return this.spelement_UnitField;
            }
            set {
                this.spelement_UnitField = value;
                this.RaisePropertyChanged("Spelement_Unit");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class tNewParcelCollection : System.Collections.Generic.List<tNewParcel> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class SchemaParcelsAppliedFileCollection : System.Collections.Generic.List<SchemaParcelsAppliedFile> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class tNewParcelContoursContourCollection : System.Collections.Generic.List<tNewParcelContoursContour> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class tSPELEMENT_UNIT_SHORTCollection : System.Collections.Generic.List<tSPELEMENT_UNIT_SHORT> {
    }
}
#pragma warning restore 1591